/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actionsmicro_airplay_AacEldEncoder */

#ifndef _Included_com_actionsmicro_airplay_AacEldEncoder
#define _Included_com_actionsmicro_airplay_AacEldEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actionsmicro_airplay_AacEldEncoder
 * Method:    init
 * Signature: (III)I
 */
JNIEXPORT jlong JNICALL Java_com_actionsmicro_airplay_airtunes_AacEldEncoder_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_actionsmicro_airplay_AacEldEncoder
 * Method:    decode
 * Signature: ([BI)[B
 */
JNIEXPORT jint JNICALL Java_com_actionsmicro_airplay_airtunes_AacEldEncoder_encode
(JNIEnv* env, jclass clazz, jlong nativeEncoder, jbyteArray data, jint length, jbyteArray out);

/*
 * Class:     com_actionsmicro_airplay_AacEldEncoder
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_actionsmicro_airplay_airtunes_AacEldEncoder_release
  (JNIEnv *, jclass, jlong nativeEncoder);

#ifdef __cplusplus
}
#endif
#endif
